port: 8080
connectionString: "someconnectionstring"
imageTargetType: "png"
processors:
  - name: OrientationProcessor
    orientation: portrait
  - name: ScaleProcessor
    height: 1920
    width: 1080
  - name: CropProcessor
    height: 1600
    width: 1200
