port: 8080
imageTargetType: "png"
database:
  type: "sqlite"
  connectionString: "file:goframe.db?cache=shared&mode=rwc"
rotationTimezone: "UTC" # Timezone for daily rotation e.g. "Europe/Berlin" or "America/New_York"
commands:
  - name: OrientationCommand
    orientation: portrait
  - name: ScaleCommand
    height: 1920
    width: 1080
  - name: CropCommand
    height: 1600
    width: 1200
  - name: DitherCommand # Floyd-Steinberg dithering algorithm
    # Custom color palette as RGB values
    palette:
      - [0, 0, 0]         # Black
      - [255, 255, 255]   # White
      - [255, 255, 0]     # Yellow
      - [0, 0, 255]       # Blue
      - [255, 0, 0]       # Red
      - [0, 255, 0]       # Green
    # if palette is not defined the following default palette will be used
    # which is designed for spectra 6 displays
    #	- [25, 30, 33]    # Black
    # - [232, 232, 232] # White
    # - [239, 222, 68]  # Yellow
    # - [178, 19, 24]   # Red
    # - [33, 87, 186]   # Blue
    # - [18, 95, 32]    # Green