apiVersion: v2
name: goframe
description: Helm chart for the goframe image processing web service
type: application
version: 1.0.2
appVersion: "1.0.2"
keywords:
  - go
  - image
  - web
sources:
  - https://github.com/jo-hoe/goframe