apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goframe.fullname" . }}-config
  labels:
    {{- include "goframe.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if .Values.configRaw }}
    {{ .Values.configRaw | nindent 4 }}
    {{- else }}
    {{- toYaml .Values.config | nindent 4 }}
    {{- end }}
